# Generated by Django 3.2.16 on 2023-05-26 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('fav_flower_family', models.CharField(choices=[('peruvian_lily', 'Peruvian Lily'), ('colchicum', 'Colchicum'), ('lily', 'Lily'), ('orchid', 'Orchid'), ('iris', 'Iris'), ('asphodel', 'Asphodel'), ('daffodil', 'Daffodil'), ('asparagus', 'Asparagus'), ('poppy', 'Poppy'), ('buttercup', 'Buttercup'), ('saxifrage', 'Saxifrage'), ('stonecrop', 'Stonecrop'), ('pea', 'Pea'), ('rose', 'Rose'), ('spurge', 'Spurge'), ('violet', 'Violet'), ('st_johns_wort', 'St Johns Wort'), ('geranium', 'Geranium'), ('loosestrife', 'Loosestrife'), ('willow_herb', 'Willow-herb'), ('mallow', 'Mallow'), ('rock_rose', 'Rock Rose'), ('cabbage', 'Cabbage'), ('sea_lavender', 'Sea Lavender'), ('pink', 'Pink'), ('phlox', 'Phlox'), ('primrose', 'Primrose'), ('heath', 'Heath'), ('periwinkle', 'Periwinkle'), ('borage', 'Borage'), ('convolvulus', 'Convolvulus'), ('nightshade', 'Nightshade'), ('olive', 'Olive'), ('plantain', 'Plantain'), ('figwort', 'Figwort'), ('mint', 'Mint'), ('acanthus', 'Acanthus'), ('verbena', 'Verbena'), ('bellflower', 'Bellflower'), ('daisy', 'Daisy'), ('umbellifer', 'Umbellifer'), ('honeysuckle', 'Honeysuckle')], default='bellflower', max_length=35)),
                ('profile_pic', models.ImageField(default='https://res.cloudinary.com/dz1h0duk6/image/upload/v1683569094/default_rqwgw0.png', upload_to='images/')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
