# Generated by Django 3.2.16 on 2023-06-14 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='https://res.cloudinary.com/dz1h0duk6/image/upload/v1686776587/orange_default_ewnird.png', upload_to='images/'),
        ),
    ]
