# Generated by Django 3.2.16 on 2023-06-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='flower_tag',
            field=models.CharField(max_length=20),
        ),
    ]
